# Generated by Django 5.2.4 on 2025-08-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='disorder_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
