# Generated by Django 5.2.4 on 2025-08-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_choice_disorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
