# Generated by Django 5.2.4 on 2025-08-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_choice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='disorder_type',
            field=models.CharField(blank=True, choices=[('GAD', 'Generalized Anxiety Disorder'), ('SAD', 'Social Anxiety Disorder'), ('PD', 'Panic Disorder'), ('OCD', 'Obsessive Compulsive Disorder'), ('PTSD', 'Post-Traumatic Stress Disorder')], max_length=100, null=True),
        ),
    ]
